src/posts/keymaps/eldritch_elder-kyria.md, src/posts/keymaps/eldritch_elder-splaytoraid40.md, src/posts/keymaps/eldritch_elder.md, src/posts/keymaps/jat.md
new keyboard and updated links to the old keymap
=> add another keymap and a lil update

src/posts/keymaps/eldritch_elder-kyria.md, src/posts/keymaps/eldritch_elder-splaytoraid40.md
forgot to take the direct links, hope they work this time
=> Fixing image links to my keymaps

src/posts/keymaps/pcoves.md
Thanks @precondition for letting me know this is possible on Discord :pray:
=> Add PCoves' layout with image

src/posts/keymaps/waffle87.md
Can `keymapUrl` take two links?
eg. `keymapUrl: "link1 link2"`
If not, I don't have any other changes to make.
Thanks :^)
=> Waffle's Keymap

src/posts/keymaps/manna_harbour.md
https://github.com/manna-harbour/miryoku_kmk
=> Add Miryoku KMK

src/posts/keymaps/frogmouth-kyria-rsthd_prime.md
=> Corrected broken links

src/posts/keymaps/braindefender-wellum.md
Added Wellum layout
Link: https://github.com/braindefender/wellum
=> Add braindefender's Wellum layout

src/posts/keymaps/minusfive.md
As it reads on the tin can.
https://github.com/minusfive/zmk-config
=> Add 👊 Knucklehead layout

src/posts/keymaps/ferrance.md
Adding dizave42 keymap in ferrance.md. thanks for your home row mods writeup :)
=> ferrance.md

src/posts/keymaps/Lysquid.md
=> Add Lysquid's keymap

src/posts/keymaps/rearman.md
My keymap for the 42 key corne, ZMK based.
=> Add rearman.md

src/posts/keymaps/frogmouth-kyria-rsthd_prime.md
Updated frogm0uth keymap for renamed branch; corrected image URL; added a key
=> Updated frogm0uth keymap for renamed branch; added a key

src/posts/keymaps/caksoylar.md
Reflect updates to the keymap:
- Key count to 28-30 and Hummingbird layout
- Remove QMK
- Mouse layer
- Update image to reflect above and make it more compact by hiding extra base layers (Bird, Gaming)
=> Update caksoylar's keymap

src/posts/keymaps/grassfedreeve.md
Apologies, can see my merge is not building due to languages not being an array so fixed that and sending in another PR
=> Fix languages to be an array on Grassfedreeve’s keymap

src/posts/keymaps/ulounge.md
Hi,
Just added my keymap file.
=> New keymap

src/posts/keymaps/haraldkubota.md
I tried many key maps and in the end I had to create my own. I hope this will be a good starting point for other people in a similar position as I was.
=> haraldkubota's Corne V4 keymap

src/posts/keymaps/ScriBanana.md
Added a keymap. Please tell me if all is not in order.
=> Added OptiCorne keymap

src/posts/keymaps/caksoylar.md
Key count update to be consistent with the config, and simplified summary.
=> Update caksoylar's keymap for 26 keys

src/posts/keymaps/isaacsa51-halcyon_kyria.md
Reading the docs after seeing that I already have 1 keymap into the site. Hope this is correct, if you see that the image doesn't show properly because of the transparency just tell me to upload a white bg one.
=> FEAT: Add Halcyon Kyria keymap

src/posts/keymaps/smallcat.md
Add my keymap for the 26 keys [Smallcat](https://github.com/smallwat3r/smallcat)
=> Add keymap for the Smallcat

src/posts/keymaps/justinmklam.md
Adds my corne keymap. Thank you!
=> Add justinmklam corne keymap

src/posts/keymaps/conner_mcnicholas.md
=> added 34 key keymap for ferris sweep keyboard

db_fields_reference.md
See #69 and #82.
Suggesting "KarabinerElements", unless there is a simple way with a space?
=> Document software based mappings

src/posts/keymaps/conner_mcnicholas.md
my formatting of the summary string value was not valid yaml...indentation hell resolved.
=> fixed yaml issue

src/posts/keymaps/valdirjunior011.md
This is a split, wireless-only mechanical keyboard  has a simple modification to include battery pads and power switches and displays
=> Temper keyboard

src/posts/keymaps/conner_mcnicholas.md
just keeping the keymap image faithful to my keymap.c file as it changes
=> new imgur link per revision
